### ISSUE TITLE
Layer names start at layer0 when they should start at layer1

### ISSUE THREAD

**Issue by MatthewMerrill** [Stanley00/anne-pro2-layout-configurator#1]
In the latest version of Obinskit, saved json files load with layer1 being the default layer, but this tool saves assuming layer0 is the default layer. Changing layer0 to layer1 works on my machine.

**Comment by Stanley00** [comment]
Should be fixed in [v0.0.2](https://github.com/Stanley00/anne-pro2-layout-configurator/releases/tag/v0.0.2)
